### ISSUE TITLE
Possible missing nonlinearity in head FC layers

### ISSUE THREAD

**Issue by dje-dev** [Rocketknight1/minimal_lczero#1]
Thank you very much for making these reference implementations available. I find them to work well (also associated data).

In ConvolutionalValueOrMovesLeftHead (both the Tensorflow and Pytorch implementations), there appears to be a possibly missing nonlinearity (relu) between the two Linear layers fc1 and fcout.

**Comment by Rocketknight1** [comment]
@dje-dev I think you're right - more specifically, I think I inserted an extra pointless `Dense` layer there compared to the original code: https://github.com/LeelaChessZero/lczero-training/blob/master/tf/tfprocess.py#L1291-L1300

I think the right solution is just to remove the `self.fc1` layer and connect the output of the conv block directly to `self.fc_out`. Alternatively I could add an activation to make the intermediate `Dense` layer actually contribute something to predictions. WDYT?

**Comment by Rocketknight1** [comment]
This issue is resolved, anyway - I removed the layer!
