### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BastiQ** [Rocketknight1/minimal_lczero#2]
Hey Rocketknight,

thanks a lot for your work! Is there a chance of you adding a license like MIT to the project? Otherwise, nobody would be allowed to copy and use your code. 

I'm just writing this because you seem to want people to use your repo to "eliminate complexity" and "allow people to try different approaches".

Thanks for considering!

**Comment by Rocketknight1** [comment]
Hey, thanks for the heads-up! Since parts of the code come from the original lczero codebase, I suspect I have to use the same licence as them, so I used GNU.
